[env:esp32devkitv1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions_ota.csv
build_flags =
  -D APP_VERSION=\"0.1.1\"
